name: Build and publish .deb package

on:
  # Permite ejecutar el workflow manualmente
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the .deb package'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show user and current directory
        run: |
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev

      - name: Show file structure for debugging
        run: |
          echo "Listing current directory:"
          ls -R  # Esto listará todo el directorio del repositorio para asegurar que los archivos están en su lugar

      - name: Set permissions
        run: |
          # Asegúrate de estar en la ruta correcta para ejecutar chmod
          ls -l ./usr/local/sbin/
          chmod 0775 ./DEBIAN/prerm
          chmod +x ./usr/local/sbin/ssp

      - name: List files before creating directory for .deb
        run: |
          echo "Listing files in the current directory before creating .deb directory:"
          ls -al

      - name: Create directory structure for .deb
        run: |
          # Crea la estructura de directorios necesaria para el paquete .deb
          mkdir -p package/DEBIAN
          mkdir -p package/usr/local/sbin
          mkdir -p package/etc/ssp
          mkdir -p package/lib/systemd/system

          # Copia los archivos al directorio correcto
          cp -r DEBIAN/* package/DEBIAN/
          cp -r usr/local/sbin/* package/usr/local/sbin/
          cp -r etc/ssp/* package/etc/ssp/
          cp -r lib/systemd/* package/lib/systemd/system/

      - name: List files before creating directory for .deb second time
        run: |
          echo "Listing files in the current directory before creating .deb directory:"
          ls -al

      - name: Build .deb package
        run: |
          # Asegúrate de usar un nombre válido para el paquete
          VERSION=${{ github.event.inputs.version }} # Obtén la versión desde la entrada
          PACKAGE_NAME="ssp-${VERSION,,}" # Convierte a minúsculas y asegúrate de que el nombre sea válido
          dpkg-deb --build package $PACKAGE_NAME.deb  # Construye el paquete .deb usando un nombre válido

      - name: Create Git tag
        run: |
          VERSION=${{ github.event.inputs.version }}
          git tag "v${VERSION}"
          git push origin "v${VERSION}"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ssp-${{ github.event.inputs.version }}.deb  # Sube el archivo .deb generado
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
