name: Build and publish .deb package

on:
  # Permite ejecutar el workflow manualmente
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the .deb package'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show user and current directory
        run: |
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev

      - name: Show file structure for debugging
        run: |
          echo "Listing current directory:"
          ls -R  # Esto listará todo el directorio del repositorio para asegurar que los archivos están en su lugar

      - name: Set permissions
        run: |
          # Asegúrate de estar en la ruta correcta para ejecutar chmod
          ls -l ./usr/local/sbin/
          chmod 0775 ./DEBIAN/prerm
          chmod +x ./usr/local/sbin/ssp

      - name: Build .deb package
        run: |
          dpkg-deb --build PrivateRepo
          mv PrivateRepo.deb ssp-${{ github.event.inputs.version }}.deb

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ssp-${{ github.event.inputs.version }}.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSP_TOKEN: ${{ secrets.SSP_TOKEN }}
